[package]
name = "crawl"
version = "1.0.0"
edition = "2024"

[dependencies]
reqwest = "0.12.14"
regex = "1.11.1"
tokio = { version = "1", features = ["full"] }
rand = "0.10.1"
dotenvy = "0.15.7"
scraper = "0.12"
encoding_rs = "0.8.35"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10"
arrow = "54.3.0"
parquet = { version = "54.3.0", features = ["arrow"] }

[dev-dependencies]
parquet = { version = "54.3.0", features = ["arrow"] }
