from __future__ import annotations

from pathlib import Path

from qa_triage.models import Cluster, ManifestEntry


def write_report(path: Path, markdown: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(markdown.rstrip() + "\n", encoding="utf-8")


def write_index(path: Path, entries: list[ManifestEntry]) -> None:
    lines = [
        "# QA root-cause reports",
        "",
        "Generated by `just qa-triage`. Each report is a fix-agent brief; triage identifies only, does not patch.",
        "",
        "| Severity | Rows | Root cause | Checks | Report |",
        "| --- | ---: | --- | --- | --- |",
    ]
    sorted_entries = sorted(
        entries,
        key=lambda e: (
            0 if e.severity in ("fail", "error") else 1,
            -e.row_count,
            e.root_cause_id,
        ),
    )
    for entry in sorted_entries:
        checks = ", ".join(f"`{c}`" for c in entry.check_ids)
        link = f"[{entry.root_cause_id}]({Path(entry.report_path).name})"
        lines.append(
            f"| {entry.severity} | {entry.row_count} | {entry.title} | {checks} | {link} |"
        )
    lines.append("")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def fallback_report(cluster: Cluster, evidence_note: str = "") -> str:
    """Dry-run placeholder when LLM is skipped."""
    checks = ", ".join(f"`{c}`" for c in cluster.check_ids)
    related = (
        ", ".join(f"`{r}`" for r in cluster.related_cluster_ids)
        if cluster.related_cluster_ids
        else "(none)"
    )
    rows_preview = "\n".join(
        f"- `{r.entity_id}`: {r.message[:200]}"
        for r in cluster.rows[:5]
    )
    return f"""# {cluster.title}

- **Root cause id:** `{cluster.root_cause_id}`
- **Severity:** {cluster.severity}
- **Affected checks:** {checks} ({cluster.row_count} rows)
- **Confidence:** low
- **Category:** (not synthesized — dry run)

## Symptom

Cluster key `{cluster.cluster_key}`. See check_docs in manifest.

## Root cause

LLM synthesis skipped (`--dry-run`). Review evidence bundle in manifest.json.

{evidence_note}

## Evidence

{rows_preview or "(parent cluster — see related_cluster_ids)"}

## Pipeline stage

(unknown — run without --dry-run)

## Files to inspect

See code_pointers in manifest.

## Suggested fix direction

Run `just qa-triage` without `--dry-run` for LLM diagnosis.

## Tests to add

Add minimal HTML/name snippets per AGENTS.md after root cause is confirmed.

## Related clusters

{related}

## Out of scope

Dry-run report only.
"""
