[package]
name = "qrva"
version = "1.0.0"
edition = "2024"

[dependencies]
crawl = { path = "../crawl" }
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
arrow = "54.3.0"
parquet = { version = "54.3.0", features = ["arrow"] }
dotenvy = "0.15.7"
zip = "2.2"
quick-xml = "0.37"

[[bin]]
name = "qrva"
path = "src/main.rs"
