[package]
name = "commissions"
version = "1.0.0"
edition = "2024"

[dependencies]
scraper = "0.12"
tokio = { version = "1", features = ["full"] }
csv = "1.1"
chrono = "0.4"
regex = "1"
crawl = { path = "../crawl" }
parquet = {  version = "54.3.0" , features = ["arrow"]}
arrow = "54.3.0"
reqwest = "0.12.14"
dotenvy = "0.15.7"

[lib]
name = "commissions"
path = "src/lib.rs"

[[bin]]
name = "commissions"
path = "src/main.rs"
